export const GET_PARTIDAS = "GET_PARTIDAS";
export const GET_PARTIDAS_ACCIONES_PROYECTOS = "GET_PARTIDAS_ACCIONES_PROYECTOS";
export const SELECT_ACCION_ESPECIFICA = "SELECT_ACCION_ESPECIFICA";
export const SELECT_MOVIMIENTOS = "SELECT_MOVIMIENTOS";

