export const BUSCAR_PERSONAL = "BUSCAR_PERSONAL";
export const AGREGAR_PERSONAL = "AGREGAR_PERSONAL";
export const SELECT_PERSONAL = "SELECT_PERSONAL";
export const GET_VALORES_GLOBALES = "GET_VALORES_GLOBALES";
export const EDIT_USER = "EDIT_USER";
export const EMPTY_EDITUSER = "EMPTY_EDITUSER";
